export const environment = {
  production: false,
  commonApiUrl: 'https://localhost:44325/Common/',
  customerHappinessServiceUrl: 'https://localhost:44325/CustomerHappiness/',
  authenticateServiceUrl: 'https://localhost:44325/Authentication/',
  recreationalFishingServiceUrl: 'https://localhost:44325/RecreationalFishing/',
  userProfileServiceUrl: 'https://localhost:44325/UserProfile/',
  permitinspectionServiceUrl: 'https://localhost:44325/RasidDispatcher/',
  rasidServiceUrl: 'https://localhost:44325/RasidInspection/',
  rasidManagerUrl: 'https://localhost:44325/RasidManager/',
  rasidQAUrl: 'https://localhost:44325/RasidQa/',
  dispatcherTeamsAndRolesServiceUrl: 'https://localhost:44325/DispatherRolesAndTeams/',
  dispatcherInvestigationUrl: 'https://localhost:44325/DispatcherInvestigations/',
  eqsCommonApiUrl: 'https://localhost:44325/EQSCommon/',
  eqsCustomerScreensForInternal: 'https://localhost:44325/EQSCustomerScreensForInternal/',
  eqsCusotomerApiUrl: 'https://localhost:44325/EQSCustomer/',
  ecoCustomerApiUrl: 'https://localhost:44325/ecoCustomer/',
  ecoTechReviewerApiUrl: 'https://localhost:44325/ECOTechReviewer/',
  eqsTechReviewerApiUrl: 'https://localhost:44325/EQSTechReviewer/',
  dispatcherDashboardUrl: 'https://localhost:44325/DispatcherDashBoard/',
  dispatcherYearlyInspectionUrl: 'https://localhost:44325/DispatcherYearlySchedule/',
  customerHappinessInvestigationsUrl: 'https://localhost:44325/CustomerHappinessInvestigations/',
  commercialFishingCommonApiUrl: 'https://localhost:44325/CommercialFishing/',
  aquacultureAPiUrl: 'https://localhost:44325/AquacultureCustomer/',
  treeTranslocation: 'https://localhost:44325/TreeTranslocation/',
  dispatcherStudyRequest: 'https://localhost:44325/DispatcherStudyRequest/',
  legalCase: 'https://localhost:44325/LegalCase/',
  groundwaterAPiUrl: "https://localhost:44325/GroundWater/",
  environment: 'Development - '
};
